AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - responses_api_gem.gemspec
    - '**/vendor/**/*'
    - '**/vendor/**/.*'

Style/Documentation:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Metrics/AbcSize:
  Max: 70

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/PerceivedComplexity:
  Max: 25

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 100

Metrics/ModuleLength:
  Max: 195

Metrics/ParameterLists:
  Max: 15

Metrics/ClassLength:
  Max: 150

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - op
    - id

Style/FrozenStringLiteralComment:
  Enabled: false
